[package]
name = "yara_false_positive"
version = "0.1.0"
edition = "2024"

[dependencies]
cryptatools-core = { git = "https://github.com/gogo2464/cryptatools-rs", package = 'cryptatools-core', version = '0.1.2' }
serde_json = "1.0.91"
itertools = "0.10.5"