[package]
name = "cryptatools-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uniffi = "*"
uniffi_macros = "*"
lingua = { version = "1.4.0", default-features = true }
assert_float_eq = "1.1.3"
approx = "*"
bimap = "*"
once_cell = "*"
itertools = "*"
rand = "0.8.5"

[build-dependencies]
uniffi_build = {version = "*", features = [ "builtin-bindgen" ]}

[lib]
name = "cryptatools_core"
crate-type = ["cdylib", "rlib"]
doctest = true
doc = true