name: Deploy bindings wheels on pypi from windows

on:
  push:
    branches:
      - master

jobs:
  deploy-wheels:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on:
      - windows-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        #ref: ${{ github.head_ref }}

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features

    - name: Install dependencies
      run: |
        pip3 install setuptools wheel twine bump2version
    
    - name: Update setup.py and Cargo.toml versions
      run: |
        cd .\cryptatools-core\
        bump2version patch .\Cargo.toml .\setup.py
        cd ..

    #- uses: actions/checkout@master
    #  with:
    #    fetch-depth: 2

    #- uses: stefanzweifel/git-auto-commit-action@v4
    #  with:
    #    commit_message: Change version with bump2version
    #    commit_user_name: gogo2464
    #    commit_user_email: gogo246475@gmail.com
    #    commit_author: gogo2464 <gogo246475@gmail.com>
    #    commit_options: '--amend --no-edit'
    #    push_options: '--force'
    #    skip_fetch: true

    - name: Build package
      run: |
        python .\cryptatools-core\setup.py bdist_wheel --verbose ;
    
    - name: Upload package
      run: |
        $wheelFile = Get-ChildItem -Path .\dist\ -Recurse -Include * ;
        #python -m twine upload $wheelFile --username gogo2464 --password ${{ secrets.PYPI_GOGO2464_PASSWORD }} --verbose ;