name: Deploy documentation from Linux stable

on:
  push:
    branches:
      - master

jobs:
  deploy-documentation:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on:
      - ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features

    - name: Install Documentation Dependencies
      run: |
        cargo install mdbook

    - name: Generate API Documentation
      run: |
        cargo doc --no-deps --package cryptatools-core --target-dir ./out
        #echo "<meta http-equiv=refresh content=0;url=`echo gogo2464/cryptatools-rs | cut -d '/' -f 2`/index.html>" > docs/index.html

    - name: Generate Four types Of Documentations
      run: |
        mdbook build docs/
    
    - name: Merge All Documentation
      run: |
        cp --force -r out/doc/* docs/book

    - name: Publish documentation
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/book
        branch: gh-pages