name: Publish Documentation Online from Ubuntu

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on:
      - ubuntu-latest
    steps:

    - name: check branch
      run: |
        if  [[ "$TRAVIS_BRANCH" == "master" ]] ; then echo 'Generating Documentation.'; else echo 'Only code on master branch can generate documentation.'; exit 0 ; fi

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features

    - name: install dependencies
      run: |
        cargo install uniffi_bindgen ;

    - name: build cryptatools
      run: cargo build

    - name: run tests
      run: |
        cargo test --all

    - name: generate documentation
      run: |
        cargo doc --target-dir ./out &&
        cp --force -r ./out/doc ./docs ;
        #echo "<meta http-equiv=refresh content=0;url=`echo gogo2464/cryptatools-rs | cut -d '/' -f 2`/index.html>" > docs/index.html

    - name: publish documentation
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs
        branch: gh-pages