name: Linux Tests
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on:
      - ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features

    - name: install dependencies
      run: |
        cargo install uniffi_bindgen ;

    - name: build cryptatools
      run: cargo build

    - name: run tests
      run: |
        cargo test --all

    - name: generate documentation
      run: |
        cargo doc