name: Linux Tests
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on:
      - ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features

    - name: Install dependencies
      run: |
        cargo install uniffi_bindgen
        pip install setuptools wheel

    - name: build cryptatools
      run: cargo build

    - name: run tests
      run: |
        cargo test --all

    - name: generate documentation
      run: |
        cargo doc
    
    - name: Build and install Python Bindings
      run: |
        python3 ./cryptatools-core/setup.py bdist_wheel --verbose ;
        pip3 install ./dist/cryptatools_python3-51.1.0-cp36-abi3-linux_x86_64.whl --force-reinstall ;
    
    - name: Test python bindings
      run: |
        python -c "from cryptatools_core.python3_bindings import CaesarNumberAlgorithm; c = CaesarNumberAlgorithm(alphabet='abc')" ;