name: Mac Os Tests
on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest]

    runs-on:
      - macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions-rs/toolchain@v1
      with:
        override: true
        toolchain: nightly

    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features

    - name: Install dependencies
      run: |
        pip3 install setuptools wheel

    - name: Build cryptatools
      run: cargo build --all

    - name: Install cryptatools clis
      run: cargo install --path ./cryptatools-cli

    - name: Run tests
      run: |
        cargo test --all

    - name: Generate documentation
      run: |
        cargo doc --package cryptatools-core --workspace --exclude clap
    
    - name: Build and install Python Bindings
      run: |
        python3 ./cryptatools-core/setup.py bdist_wheel --verbose ;
        pip3 install ./dist/* --force-reinstall ;
    
    - name: Test python bindings
      run: |
        python3 ./cryptatools-core/binding-testing/testing.py ;
