name: Mac Os Tests
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on:
      - macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features
    - name: install uniffi_bindgen with cargo
      run: cargo install uniffi_bindgen
    - name: install cryptatools
      run: cargo build
    - name: run tests
      run: |
        cargo test  --all