name: Test documentation on Linux nightly

on:
  push:
    branches:
      - master

jobs:
  deploy-documentation:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on:
      - ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features

    - name: Generate documentation
      run: |
        cargo doc --package cryptatools-core --workspace --no-deps #--exclude clap,rustix
