name: Windows Tests
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on:
      - windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features

    - name: Install dependencies
      run: |
        cargo install uniffi_bindgen
        pip3 install setuptools wheel

    - name: Build cryptatools
      run: cargo build

    - name: Run tests
      run: |
        cargo test --all

    - name: Generate documentation
      run: |
        cargo doc
    
    - name: Build and install Python Bindings
      run: |
        python .\cryptatools-core\setup.py bdist_wheel --verbose ;
        $wheelFile = Get-ChildItem -Path .\dist\ -Recurse -Include * ;
        pip3 install $wheelFile --force-reinstall ;
        
    
    - name: Test python bindings
      run: |
        python -c "from cryptatools_core.python3_bindings import CaesarNumberAlgorithm; c = CaesarNumberAlgorithm(alphabet={'a': [0x61], 'b': [0x62], 'c': [0x63]})" ;