name: Windows Tests
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on:
      - windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features

    - name: Install dependencies
      run: |
        cargo install uniffi_bindgen
        pip install setuptools wheel

    - name: Install cryptatools
      run: cargo build

    - name: Run tests
      run: |
        cargo test --all
    
    - name: Build and install Python Bindings
      run: |
        python .\cryptatools-core\setup.py bdist_wheel --verbose ;
        pip3 install .\dist\cryptatools_python3-51.1.0-py3-none-win_amd64.whl --force-reinstall ;
    
    - name: Test python bindings
      run: |
        python -c "from cryptatools_core.python3_bindings import CaesarNumberAlgorithm; c = CaesarNumberAlgorithm(alphabet='abc') ;"