name: Windows Tests
on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on:
      - windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features

    - name: Install dependencies
      run: |
        # cargo install uniffi_bindgen
        pip3 install setuptools wheel

    - name: Build cryptatools
      run: cargo build --all

    - name: Install cryptatools clis
      run: cargo install --path .\cryptatools-cli

    - name: Run tests
      run: |
        cargo test --all

    - name: Generate documentation
      run: |
        cargo doc --package cryptatools-core
    
    - name: Build and install Python Bindings
      run: |
        python .\cryptatools-core\setup.py bdist_wheel --verbose ;
        $wheelFile = Get-ChildItem -Path .\dist\ -Recurse -Include * ;
        pip3 install $wheelFile --force-reinstall ;
        
    
    - name: Test python bindings
      run: |
        python .\cryptatools-core\binding-testing\testing.py ;
